import {useEffect,useRef,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {api,pause} from './api'
import {MapView} from './MapView'
import {DynamicMission} from './DynamicMission'
import {affectedTasks,entity,eventText,modes,runLabel,titles} from './presentation'
import {AssessmentCards,Boundaries,Brief,Changes,DecisionPanel,FeedbackStory,ImpactPanel,Outcome,ScenarioCards,Technical,TechnologyChain,Timing,ValidationPanel} from './Narrative'
import type {Mode,Scenario,Session,Run,Job,Replay,Metrics} from './types'
import './style.css'

function App({onDynamic}:{onDynamic:()=>void}){
 const [scenarios,setScenarios]=useState<Scenario[]>([]),[scenario,setScenario]=useState('SC08'),[mode,setMode]=useState<Mode>('deterministic_realtime')
 const [session,setSession]=useState<Session|null>(null),[run,setRun]=useState<Run|null>(null),[initialMetrics,setInitialMetrics]=useState<Metrics>()
 const [busy,setBusy]=useState(false),[running,setRunning]=useState(false),[error,setError]=useState(''),[stepMode,setStepMode]=useState(true),[stage,setStage]=useState(0)
 const [view,setView]=useState<'before'|'after'|'overlay'>('after'),[focus,setFocus]=useState(''),[selected,setSelected]=useState(''),[progress,setProgress]=useState('选择一个场景，开始逐步讲解。')
 const [replays,setReplays]=useState<Replay[]>([]),[replay,setReplay]=useState(false),[replayId,setReplayId]=useState(''),[traceLimit,setTraceLimit]=useState<number|null>(null),[showDiagnostics,setShowDiagnostics]=useState(false)
 const mounted=useRef(true)
 useEffect(()=>{mounted.current=true;api<Scenario[]>('/scenarios').then(setScenarios).catch(()=>setError('场景列表读取失败，请确认后端已启动。'));refreshRuns();return()=>{mounted.current=false}},[])
 function refreshRuns(){api<Replay[]>('/runs').then(setReplays).catch(()=>{})}
 async function perform(action:()=>Promise<void>){setBusy(true);setError('');try{await action()}catch(e){setError(String(e));setProgress('操作未完成，现场状态以已提交结果为准。')}finally{if(mounted.current){setBusy(false);setRunning(false)}}}
 async function load(id=scenario){const d=await api<Session>('/session',{scenario_id:id});setScenario(id);setSession(d);setInitialMetrics(d.metrics);setRun(null);setReplay(false);setReplayId('');setTraceLimit(null);setStage(1);setView('after');setFocus('');setSelected('');setProgress('初始场景已加载。下一步注入预设事件。');return d}
 async function inject(d:Session){const next=await api<Session>('/event',{session_id:d.session_id,expected_version:d.state.version,all_remaining:true});setSession(next);setStage(2);setView('after');setProgress('事件已生效，影响传播与约束评估已完成。可查看因果链或运行重构。');return next}
 async function reconstruct(d:Session,auto:boolean){setRunning(true);setProgress(`${modes[mode].name}正在执行，等待真实工具与校核结果。`);const job=await api<Job>('/reconstruct',{session_id:d.session_id,expected_version:d.state.version,mode,auto_commit:auto});for(;;){await pause(350);if(!mounted.current)return;const result=await api<Run|Job>('/run/'+job.run_id);if(result.status==='RUNNING')continue;const r=result as Run;setRun(r);setRunning(false);setStage(r.status==='READY'?4:5);setView('overlay');setProgress(r.status==='READY'?'候选方案已通过校核。现场尚未改变，请确认后提交。':r.status==='COMMITTED'?'全局校核通过，重构方案已提交。':r.status==='NO_RECONSTRUCTION_REQUIRED'?'当前已建模硬约束满足，无需重构。':'重构未完成，失败方案未提交到现场。');refreshRuns();return}}
 async function finalDemo(){let d=await load('SC08');await pause(800);d=await inject(d);await pause(1200);setStage(3);await reconstruct(d,true)}
 async function replayRun(id:string){const r=await api<Run>('/run/'+id);setRun(r);setMode(r.execution_mode);setScenario(r.scenario.scenario_id);setSession(null);setReplay(true);setReplayId(id);setTraceLimit(1);setStage(5);setView('overlay');setFocus('');setSelected('');setProgress('历史回放：状态为该次最终记录；下方逐条展示决策，不重新调用模型或提交。')}
 const current=run?.after_state??session?.state,before=run?.before_state??session?.initial_state
 const candidate=run?.status==='READY'&&run.candidate_state?run.candidate_state:current
 const metrics=run?.before_after_metrics.after??session?.metrics
 let mapMetrics=view==='before'?(run?.before_after_metrics.before??initialMetrics):metrics
 if(view!=='before'&&run?.status==='READY'&&run.validation?.status!=='FAIL'&&mapMetrics)mapMetrics={...mapMetrics,invalid_formations:[],invalid_routes:[],violations:[]}
 const impacts=run?.impact_analysis??session?.impact_analysis??[],assessments=run?.task_assessment??session?.task_assessment??[],events=run?.event??session?.planned_events??[]
 const injected=Boolean(run||session?.impact_analysis.length),activeMode=run?.execution_mode??mode,activeScenario=run?.scenario??session?.scenario
 const steps=run?.trace_steps??[],visibleSteps=steps.slice(0,traceLimit??steps.length)
 const shownState=view==='before'?before:candidate
 const selectedEntity=shownState?[...shownState.nodes,...shownState.formations,...shownState.tasks,...shownState.routes,...shownState.environment].find(x=>x.id===selected):undefined
 const viewNames={before:run?'态势变化后 / 重构前':'初始方案',after:run?.status==='READY'?'待提交方案':run?.commit?'重构后方案':'当前方案',overlay:run?'叠加对比':'事件前后对比'}
 const mapCaption=view==='overlay'?(run?'原方案与重构方案叠加对比':'初始方案与态势变化后的方案对比'):view==='before'?(run?'态势变化后、重构之前的任务方案':'事件尚未发生的初始任务方案'):run?.status==='READY'?'候选方案预览，尚未现场提交':run?.commit?'重构后已提交的任务方案':injected?'态势变化后的任务方案':'初始任务方案'
 return <div className="app-shell"><header><div><span className="kicker">集群任务重构智能体 · 场景验证</span><h1>技术可解释任务重构控制台</h1></div><div className="header-actions"><span className="header-note">真实数据 · 独立校核 · 可追溯执行</span><button className="dynamic-entry" onClick={onDynamic}>动态任务演示</button></div></header>
 <div className="toolbar"><label>演示场景<select id="scenario" value={scenario} disabled={busy} onChange={e=>setScenario(e.target.value)}>{scenarios.filter(s=>s.default_visible||showDiagnostics).map(s=><option key={s.scenario_id} value={s.scenario_id}>{s.scenario_id} · {titles[s.scenario_id]??s.name}{s.default_visible?'':'（部分支持）'}</option>)}</select></label><div className="mode-control"><span>执行模式{run?` · 当前结果：${modes[run.execution_mode].name}`:''}</span><div className="segmented" aria-label="执行模式">{(Object.keys(modes) as Mode[]).map(m=><button key={m} className={mode===m?'active':''} disabled={busy} onClick={()=>setMode(m)}>{modes[m].name}</button>)}</div><small>{modes[mode].note}{run&&mode!==run.execution_mode?'（此选择用于下次运行）':''}</small></div><button className="primary" disabled={busy} onClick={()=>perform(finalDemo)}>一键综合演示</button></div>
 <nav className="workflow" aria-label="演示步骤"><label><input type="checkbox" checked={stepMode} disabled={busy} onChange={e=>setStepMode(e.target.checked)}/>分步讲解</label><button disabled={busy} onClick={()=>perform(async()=>{await load()})}>加载场景</button><button disabled={busy||!session||replay||!session.remaining_events.length||!!run} onClick={()=>perform(async()=>{if(session)await inject(session)})}>1 注入事件</button><button disabled={busy||!injected} onClick={()=>{setStage(Math.max(stage,3));document.getElementById('impact-section')?.scrollIntoView({behavior:'smooth',block:'start'})}}>2 查看影响原因</button><button disabled={busy||!session||stage<2||!!run||replay} onClick={()=>perform(async()=>{if(session)await reconstruct(session,!stepMode)})}>3 运行重构</button><button disabled={busy||run?.status!=='READY'||replay} onClick={()=>perform(async()=>{if(run){const r=await api<Run>('/commit',{run_id:run.run_id});setRun(r);setStage(5);setProgress('现场全局再次校核通过，方案已事务化提交。');refreshRuns()}})}>4 校核并提交</button><span className="workflow-progress" role="status">{busy&&<i className="spinner"/>}{progress}</span></nav>
 <main>{error&&<div className="notice error" role="alert">操作失败，请检查服务或当前版本。<Technical title="错误技术详情" value={error}/></div>}{run?.error&&<div className="notice error">{run.error.code==='MODEL_NOT_CONFIGURED'?'尚未配置模型凭据，可使用实时确定性模式。':'智能体策略未能完成本次重构，现场未发布失败方案。'}<Technical title="错误技术详情" value={run.error}/></div>}{Boolean(run?.policy_metrics.fallback_used)&&<div className="notice warning" data-testid="fallback-notice">已切换确定性后备：本次结果不计为智能体自主完成。<Technical value={run?.policy_metrics}/></div>}{activeScenario&&!activeScenario.default_visible&&<div className="notice warning">部分支持：冗余能力的局部评估可保持任务，但全局规则仍禁止执行编队保留失效节点，不能宣称无需重构。</div>}{run?.status==='READY'&&<div className="notice preview">候选方案已校核，但现场尚未提交。地图与拟修改内容展示候选；顶部与恢复结果仍展示真实现场。</div>}
 {!current&&<><section className="experience-switch"><article className="selected"><div><span>STANDARD VALIDATION</span><b>标准技术验证</b><p>SC01–SC08 固定场景 · 固定事件 · 单轮重构 · 指标对比与验证回放</p></div><em>当前页面</em></article><article className="dynamic-choice"><div><span>DYNAMIC MISSION</span><b>动态随机任务</b><p>随机布局 · 节点持续运动 · 运行时事件 · 同一任务多轮在线重构</p></div><button className="primary" onClick={onDynamic}>生成随机任务并持续运行 →</button></article></section><div className="welcome"><h2>标准技术验证</h2><p>选择一个固定场景，按照“注入事件—影响分析—重构—校核提交”完成可重复验证。</p></div><ScenarioCards scenarios={scenarios} busy={busy} onLoad={id=>perform(async()=>{if(id==='SC07')setMode('adaptive_agent');await load(id)})}/><details className="panel secondary"><summary>其他场景与支持范围</summary><div className="other-scenarios">{scenarios.map(s=><article key={s.scenario_id}><h3>{s.scenario_id} · {titles[s.scenario_id]??s.name}</h3><p>规模：{s.node_count} 个节点 / {s.task_count} 项任务 / {s.formation_count} 个编队</p><p>事件：{s.event_count} 项；影响：注入后评估</p><p>展示技术：{s.diagnostic_seed?'全局冲突反馈与智能重规划':'影响评估、局部重构与全局校核'}</p><p>{s.default_visible?'支持当前演示链路':'部分支持，诊断用；不能宣称全局无需重构'}</p><button disabled={busy} onClick={()=>perform(async()=>{if(!s.default_visible)setShowDiagnostics(true);if(s.diagnostic_seed)setMode('adaptive_agent');await load(s.scenario_id)})}>加载 {s.scenario_id}</button></article>)}</div></details></>}
 {current&&metrics&&<Brief state={current} metrics={metrics} events={events} impacts={impacts} assessments={assessments} injected={injected} run={run} replay={replay}/>}
 <TechnologyChain stage={stage} running={running} run={run} mode={activeMode} impacts={impacts} assessments={assessments}/>
 {!current&&<section className="panel introduction"><h2>系统如何分工？</h2><Boundaries/><p>模型选择策略，算法生成具体方案，全局校核器独立检查。只有合法方案才能提交。</p></section>}
 {current&&before&&candidate&&mapMetrics&&<><div className="map-story" id="impact-section"><section className="panel map-panel"><div className="section-heading"><div><span className="eyebrow">MISSION PLAN</span><h2>任务态势与方案对比</h2></div><div className="segmented compact">{(['before','after','overlay'] as const).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{viewNames[v]}</button>)}</div></div><p className="map-caption" data-testid="map-caption">{mapCaption}</p><p className="map-guide">圆点为平台位置，菱形为任务目标；粗实线为航迹，细虚线为编队成员关系。数量标签表示同坐标节点数。</p><div className="focus-controls"><span>任务过滤</span><button className={!focus?'active':''} onClick={()=>setFocus('')}>全部任务</button>{affectedTasks(impacts).map(id=><button key={id} className={focus===id?'active':''} onClick={()=>setFocus(id)}>{entity(id)}</button>)}</div><MapView before={before} after={candidate} view={view} metrics={mapMetrics} focusTask={focus} onSelect={setSelected}/><div className="legend"><span>● 正常节点</span><span className="red-text">⊗ 失效节点</span><span className="green-text">● 归属变化节点</span><span className="orange-text">◇ 受影响任务目标</span><span>━━ 当前航迹</span><span>┄┄ 原航迹</span><span className="red-text">▨ 限制区域</span></div>{injected&&<div className="map-look"><b>事件与方案变更</b>{events.filter(e=>['NodeFailure','RestrictedAreaAdd','TargetMove'].includes(e.type)).map(e=><span key={e.event_id}>{eventText(e)}</span>)}{run?.reconstruction_proposal?.route_changes.map(r=><span key={r.route_id}>{entity(r.route_id)} 新航迹</span>)}</div>}{selectedEntity&&<Technical title={entity(selected)+' · 实体技术详情'} value={selectedEntity}/>}</section><ImpactPanel impacts={impacts} assessments={assessments} events={events} state={run?.before_state??current} onFocus={id=>{setFocus(id);document.getElementById('impact-section')?.scrollIntoView({behavior:'smooth'})}}/></div><AssessmentCards assessments={assessments} state={run?.before_state??current}/></>}
 {running&&<section className="panel processing"><i className="spinner"/><h2>正在生成并校核重构方案</h2><p>{modes[mode].note}内部工具逐步结果将在本次运行返回后展示。</p></section>}
 {run&&<>{replay&&<div className="panel replay-controls"><b>决策过程回放</b><button onClick={()=>setTraceLimit(Math.min((traceLimit??steps.length)+1,steps.length))}>下一条决策</button><button onClick={()=>setTraceLimit(null)}>展示完整过程</button><span>已显示 {traceLimit??steps.length} / {steps.length} 条；地图和结果保持该次最终记录。</span></div>}<FeedbackStory key={run.run_id} run={run} steps={visibleSteps}/><Outcome run={run}/><Changes run={run}/><DecisionPanel run={run} visibleSteps={visibleSteps}/><div className="validation-timing">{run.validation&&<ValidationPanel validation={run.validation} committed={Boolean(run.commit)}/>}<Timing run={run}/></div><details className="panel secondary"><summary>完整技术详情｜事件、依赖路径、方案、模型用量与原始记录</summary><p>记录中的内部求解在隔离分支完成，只有最后的现场事务回执代表已发布。</p><a href={'/api/v1/demo/run/'+run.run_id} target="_blank" rel="noreferrer">查看原始运行记录</a><Technical title="原始运行数据" value={run}/></details></>}
 <section className="panel replay-bar"><div><h2>真实运行回放</h2><p>读取已保存状态和决策，不重复调用模型、不修改现场。</p></div><select aria-label="历史运行" value={replayId} disabled={busy} onChange={e=>e.target.value&&perform(()=>replayRun(e.target.value))}><option value="">选择一条已保存的运行记录</option>{replays.map(r=><option key={r.run_id} value={r.run_id}>{r.scenario_id} · {modes[r.execution_mode].name} · {runLabel(r.status)} · {r.created_at.slice(11,19)} UTC</option>)}</select></section><label className="diagnostic-toggle"><input type="checkbox" checked={showDiagnostics} onChange={e=>setShowDiagnostics(e.target.checked)}/>在选择器中显示部分支持的诊断场景</label>
 </main><footer>事件与影响 → 策略与重构 → 全局校核 → 可信提交<span>当前为二维任务示意；未评估的物理与调度约束始终明示。</span></footer></div>
}
function Root(){const [surface,setSurface]=useState<'standard'|'dynamic'>('standard');return surface==='standard'?<App onDynamic={()=>setSurface('dynamic')}/>:<DynamicMission onStandard={()=>setSurface('standard')}/>}
createRoot(document.getElementById('root')!).render(<Root/>);
