import {useState} from 'react'
import type {Assessment,DemoEvent,Impact,Json,Metrics,Mode,Run,Scenario,State,TraceStep,Validation} from './types'
import {affectedTasks,capability,capabilityRows,categories,decisionSummary,decisions,dependencyGraph,entity,eventCounts,eventText,feedbackChecks,impactChains,issueText,limitations,modes,object,preservation,readablePath,reasons,stages,strategies,taskName,time,titles,tools,validationLabel} from './presentation'

export function Technical({title='技术详情',value}:{title?:string;value:unknown}){return <details className="technical"><summary>{title}</summary><pre>{JSON.stringify(value,null,2)}</pre></details>}
export function Stat({label,value,note,tone=''}:{label:string;value:React.ReactNode;note?:string;tone?:string}){return <div className={'stat '+tone}><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
export function ScenarioCards({scenarios,onLoad,busy}:{scenarios:Scenario[];onLoad:(id:string)=>void;busy:boolean}){return <section className="scenario-cards" aria-label="场景选择">{['SC08','SC07','SC03'].map((id,i)=>{const s=scenarios.find(s=>s.scenario_id===id);return s&&<button key={id} disabled={busy} onClick={()=>onLoad(id)}><span className="kicker">{['主演示','智能体技术演示','基础技术演示'][i]}</span><h2>{id} · {titles[id]}</h2><p>{s.node_count} 个节点 / {s.task_count} 项任务 / {s.formation_count} 个编队</p><p>事件：{s.event_count} 项预设态势变化</p><p>{s.description.replaceAll('relay','中继能力').replaceAll('TargetMove','目标移动')}</p><p>影响：注入事件后由实际评估给出</p><b>{['影响传播 · 编队修复 · 航迹重规划','全局冲突反馈 · 扩大范围 · 再次校核','候选资源竞争 · 最小扰动修复'][i]}</b><span className="card-action">加载并逐步讲解 →</span></button>})}</section>}
export function Brief({state,metrics,events,impacts,assessments,injected,run,replay}:{state:State;metrics:Metrics;events:DemoEvent[];impacts:Impact[];assessments:Assessment[];injected:boolean;run:Run|null;replay:boolean}){const affected=affectedTasks(impacts);const gaps=assessments.filter(a=>capabilityRows(a).some(g=>Number(g.gap)>0));return <section className={'brief panel '+(metrics.violations.length?'attention':'restored')} data-testid="scenario-brief"><div className="brief-heading"><div><span className="kicker">{replay?'历史运行回放':'当前场景'} · {state.scenario_id}</span><h1>{run?.commit?'任务方案已恢复并提交':injected?'综合态势发生变化':titles[state.scenario_id]??'任务重构场景'}</h1><p>当前集群由 <b>{state.nodes.length} 个节点</b>、<b>{state.formations.length} 个编队</b>执行 <b>{state.tasks.filter(t=>t.status==='ACTIVE').length} 项任务</b>。</p></div><div className={'plan-state '+(metrics.violations.length?'invalid':'valid')} data-testid="plan-status">{run?.status==='READY'?'候选已校核，现场仍待提交':metrics.violations.length?'当前方案需要重构':'当前已建模约束可行'}</div></div><div className="event-story"><b>{injected?'已经发生':'预设事件，尚未注入'}：</b>{eventCounts(events)||'当前无事件'}<details><summary>查看具体事件</summary><ul>{events.map(e=><li key={e.event_id}>{eventText(e)}</li>)}</ul></details></div><div className="summary-stats"><Stat label="当前可行任务" value={`${metrics.feasible_tasks}/${metrics.task_count}`} tone={metrics.violations.length?'orange':'green'}/><Stat label="失效节点" value={metrics.nodes.FAILED??0} tone="red"/><Stat label="本轮受影响任务" value={injected?affected.length:'待评估'} note={affected.map(entity).join('、')}/><Stat label="当前能力缺口" value={metrics.capability_gap} note={injected?`事件后 ${gaps.length} 项任务存在能力缺口`:'事件尚未发生'}/><Stat label="当前无效航迹" value={metrics.invalid_routes.length}/></div>{events.some(e=>e.type==='TaskPriorityChange')&&<p className="muted">优先级变化作为输入与策略排序属性展示；动态任务调度尚未纳入校核。</p>}</section>}
export function TechnologyChain({stage,running,run,mode,impacts=[],assessments=[]}:{stage:number;running:boolean;run:Run|null;mode:Mode;impacts?:Impact[];assessments?:Assessment[]}){
 const affected=affectedTasks(impacts).length,violations=assessments.filter(a=>a.decision!=='KEEP').length
 const generated=Boolean(run?.reconstruction_proposal),validated=Boolean(run?.validation),committed=Boolean(run?.commit)
 const status=(ready:boolean,active=false)=>ready?'done':active?'active':'waiting'
 const validatorStatus=run?.validation?.status==='FAIL'?'failed':status(validated)
 const controller=mode==='deterministic_realtime'?'确定性基线控制器':'Agent Policy'
 return <section className="panel architecture" aria-label="系统数据流与执行链" data-testid="system-pipeline">
  <div className="section-heading"><div><span className="eyebrow">SYSTEM ORCHESTRATION</span><h2>系统数据流与执行链</h2></div><span>{running?'重构任务执行中':committed?'状态版本已更新':'状态、方案与提交边界分离'}</span></div>
  <div className="layered-pipeline">
   <div className="pipeline-lane"><b className="lane-name">数据层</b><div className="lane-track"><div className={'flow-node '+status(stage>=1)}><strong>状态与事件数据</strong><small>State v{run?.before_state.version??'—'} · Event</small></div><i>→</i><div className={'flow-node '+status(stage>=2)}><strong>TRDG 影响传播</strong><small>{affected} 项任务进入影响域</small></div><i>→</i><div className={'flow-node '+status(stage>=2)}><strong>约束事实集</strong><small>{violations} 项任务需要调整</small></div></div></div>
   <div className="pipeline-lane"><b className="lane-name">决策层</b><div className="lane-track"><div className={'flow-node controller '+status(generated,running)}><strong>{controller}</strong><small>{mode==='deterministic_realtime'?'固定分层策略 · 0 次模型调用':`模型调用 ${String(run?.policy_metrics.model_calls??0)} 次`}</small></div><span className="feedback-return">校核反馈 ↺ 策略重规划</span></div></div>
   <div className="pipeline-lane"><b className="lane-name">原语工具调度</b><div className="lane-track tools-track">{['候选生成','原位修复 / 任务改派','编队重组','航迹影响检测','A* 航迹规划'].map((name,i)=><div className={'flow-node '+status(generated,running)} key={name}><span className="node-index">0{i+1}</span><strong>{name}</strong></div>)}</div></div>
   <div className="pipeline-lane"><b className="lane-name">安全执行层</b><div className="lane-track"><div className={'flow-node '+status(generated)}><strong>Proposal</strong><small>隔离分支候选状态</small></div><i>→</i><div className={'flow-node '+validatorStatus}><strong>Global Validator</strong><small>{run?.validation?`${run.validation.metrics.hard_constraint_count} 项硬约束`:'独立全局校核'}</small></div><i>→</i><div className={'flow-node '+status(committed)}><strong>事务化提交</strong><small>{committed?`State v${run!.commit!.committed_version}`:'版本 / 幂等 / 原子发布'}</small></div></div></div>
  </div>
 </section>
}
export function Boundaries(){return <div className="boundaries"><div><b>智能体策略</b><span>决定采用哪种重构策略</span></div><span>→</span><div><b>确定性算法</b><span>计算具体可行方案</span></div><span>→</span><div><b>全局校核器</b><span>判断是否允许提交</span></div></div>}
export function TRDGGraph({impacts,events,onFocus}:{impacts:Impact[];events:DemoEvent[];onFocus:(id:string)=>void}){
 const graph=dependencyGraph(impacts,events),columns=[0,1,2,3].map(c=>graph.nodes.filter(n=>n.column===c))
 const height=Math.max(258,...columns.map(c=>c.length*76+62)),xs=[110,350,590,830],positions=new Map<string,{x:number;y:number}>()
 columns.forEach((nodes,column)=>nodes.forEach((node,row)=>positions.set(node.id,{x:xs[column],y:62+row*76})))
 return <div className="trdg-wrap"><div className="trdg-columns"><span>态势源</span><span>任务结构</span><span>能力事实</span><span>受影响任务</span></div><svg className="trdg-graph" viewBox={`0 0 940 ${height}`} role="img" aria-label="TRDG 任务依赖图">
  <defs><marker id="trdg-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z"/></marker></defs>
  <g className="trdg-edges">{graph.edges.map(edge=>{const a=positions.get(edge.from),b=positions.get(edge.to);return a&&b?<path key={edge.from+edge.to} data-edge={`${edge.from}>${edge.to}`} d={`M${a.x+78},${a.y} C${a.x+125},${a.y} ${b.x-125},${b.y} ${b.x-78},${b.y}`} markerEnd="url(#trdg-arrow)"/>:null})}</g>
  {graph.nodes.map(node=>{const p=positions.get(node.id)!;const clickable=node.kind==='task';return <g key={node.id} className={`trdg-node ${node.kind} ${clickable?'clickable':''}`} transform={`translate(${p.x-78} ${p.y-25})`} onClick={()=>clickable&&onFocus(node.id.split(':').at(-1)!)}><rect width="156" height="50" rx="5"/><text x="78" y="21" textAnchor="middle">{node.label.length>16?node.label.slice(0,15)+'…':node.label}</text><text className="trdg-id" x="78" y="38" textAnchor="middle">{node.id}</text></g>})}
 </svg></div>
}
export function ImpactPanel({impacts,assessments,events,state,onFocus}:{impacts:Impact[];assessments:Assessment[];events:DemoEvent[];state:State;onFocus:(id:string)=>void}){const chains=impactChains(impacts);return <section className="panel impacts" data-testid="impact-panel"><div className="section-heading"><div><span className="eyebrow">TRDG · IMPACT PROPAGATION</span><h2>TRDG 任务依赖图</h2></div><span>{chains.length} 条任务影响链</span></div>{chains.length?<><TRDGGraph impacts={impacts} events={events} onFocus={onFocus}/><div className="impact-results">{chains.map(c=>{const a=assessments.find(a=>a.task_id===c.task);return <article className="cause-card" key={c.task} data-testid={'cause-'+c.task}><button className="text-button" onClick={()=>onFocus(c.task)}>{taskName(c.task,state)} ↗</button><div className="cause-path">{readablePath(c.path,events).map((p,i)=><span key={i}>{i>0&&<i>→</i>}{p}</span>)}</div>{a&&<><p className="issue">{issueText(a)}</p><b className={a.decision==='KEEP'?'green-text':'orange-text'}>{decisions[a.decision]??'状态待确认'}</b></>}</article>})}</div></>:<p className="empty">事件注入后生成任务依赖子图与传播路径。</p>}</section>}
export function AssessmentCards({assessments,state}:{assessments:Assessment[];state:State}){return <details className="panel secondary"><summary>任务状态评估｜能力、资源、编队、航迹与时间约束</summary><p className="muted">以下为事件后、重构前的局部评估。局部满足不替代全局校核。</p><div className="assessment-grid">{assessments.map(a=><article className="assessment" key={a.task_id}><h3>{taskName(a.task_id,state)}</h3><b>{decisions[a.decision]??'状态待确认'}</b><table><thead><tr><th>能力</th><th>需求</th><th>当前</th><th>缺口</th></tr></thead><tbody>{capabilityRows(a).map(c=><tr key={c.key}><td>{capability[c.key]??'能力 '+c.key}</td><td>{String(c.required)}</td><td>{String(c.available)}</td><td className={Number(c.gap)>0?'red-text':'green-text'}>{String(c.gap)}</td></tr>)}</tbody></table>{a.constraints.map(c=><div className="status-line" key={c.type}><span>{categories[c.type]??'其他约束'}</span><b className={c.status==='FAIL'?'red-text':'green-text'}>{c.status==='PASS'?'满足':c.status==='FAIL'?'不满足':'未评估'}</b></div>)}<p className="muted">时间项仅限已实现检查；真实飞行时间和动态调度仍未评估。</p></article>)}</div></details>}
export function CandidateFunnel({run}:{run:Run}){const sets=run.reconstruction_proposal?.trace?.candidate_sets??[];const [index,setIndex]=useState(0);const current=sets[Math.min(index,sets.length-1)];if(!current)return null;return <section className="candidate-funnel" data-testid="candidate-funnel"><div className="subsection-heading"><div><span className="eyebrow">CANDIDATE FILTER</span><h3>候选资源筛选</h3></div><select aria-label="候选筛选轮次" value={Math.min(index,sets.length-1)} onChange={e=>setIndex(Number(e.target.value))}>{sets.map((s,i)=><option value={i} key={i}>{entity(s.task_id)} · {strategies[s.strategy_level]??'候选筛选'} · #{i+1}</option>)}</select></div><div className="funnel">{current.stages.filter(s=>stages[s.name]).map((s,i)=><div key={i}><span>{stages[s.name]}</span><b>{s.remaining}</b><div style={{width:`${100*s.remaining/Math.max(1,current.stages[0]?.remaining??1)}%`}}/></div>)}</div><div className="candidate-result"><span>可用候选</span><strong>{current.candidates.map(c=>entity(c.node_id)).join(' · ')||'无'}</strong></div></section>}
export function RoutePlanningFlow({run}:{run:Run}){const changes=run.reconstruction_proposal?.route_changes??[];if(!changes.length)return null;return <section className="route-flow" data-testid="route-flow"><div className="subsection-heading"><div><span className="eyebrow">ROUTE REPLANNING</span><h3>航迹重规划</h3></div><span>A* · 连续线段碰撞检测</span></div>{changes.map(change=>{const result=run.deterministic_trace?.route_results?.find(r=>r.task_id===change.task_id);return <div className="route-track" key={change.route_id}><div><b>影响检测</b><span>{change.reason_codes?.some(c=>c.includes('RESTRICTED'))?'限制区域相交':'航迹约束变化'}</span></div><i>→</i><div><b>栅格建模</b><span>{run.before_state.bounds.grid_resolution??10} 单位分辨率</span></div><i>→</i><div><b>A* 搜索</b><span>{result?`扩展 ${result.expanded_cells} 个节点`:'有界路径搜索'}</span></div><i>→</i><div><b>几何校核</b><span>{result?.reason_codes.includes('CONTINUOUS_SEGMENT_CHECK_PASSED')?'连续线段检查通过':'候选路径检查'}</span></div><i>→</i><div className="selected"><b>{entity(change.route_id)}</b><span>长度 {change.path_length.toFixed(1)}</span></div></div>})}</section>}
export function DecisionPanel({run,visibleSteps}:{run:Run;visibleSteps:TraceStep[]}){return <section className="panel decisions"><div className="section-heading"><div><span className="eyebrow">RECONSTRUCTION ORCHESTRATION</span><h2>重构调度与算法执行</h2></div><span className="mode-label" data-testid="current-mode">{modes[run.execution_mode].name} · 模型调用 {String(run.policy_metrics.model_calls??0)} 次</span></div><Boundaries/><CandidateFunnel run={run}/><RoutePlanningFlow run={run}/><details className="secondary inset"><summary>执行记录 · {visibleSteps.length} 条</summary><div className="decision-grid">{visibleSteps.map(s=><article key={s.step} className={'decision-card '+(object(s.feedback).status==='FAIL'?'rejected':'')}><span className="eyebrow">{s.kind==='LIVE_TRANSACTION'?'LIVE TRANSACTION':s.kind==='DETERMINISTIC_BASELINE'?'DETERMINISTIC':'AGENT'} · {s.step}</span><h3>{s.option?strategies[s.option.strategy]??'选择重构方案':tools[s.tool]??'重构技能执行'}</h3>{s.option&&<><p className="issue">{issueText(run.task_assessment.find(a=>a.task_id===s.option!.task)??{task_id:s.option.task,decision:'RECONSTRUCT',reason_codes:[],constraints:[]})}</p><p>{entity(s.option.task)} · {entity(s.option.formation)}</p><p>移出：{s.option.remove.map(entity).join('、')||'无'}<br/>加入：{s.option.add.map(entity).join('、')||'无'}</p><p className="muted">{s.option.cost[0]===0?'任务归属保持':'包含任务改派'} · {s.option.cost[4]===0?'航迹保持':'包含航迹调整'}</p></>}<p>{decisionSummary(s)}</p>{s.feedback&&<strong className={object(s.feedback).status==='FAIL'?'red-text':'green-text'}>{validationLabel(String(object(s.feedback).status))}</strong>}<Technical value={s}/></article>)}</div></details></section>}
export function FeedbackStory({run,steps}:{run:Run;steps:TraceStep[]}){const checks=feedbackChecks(steps);const failed=checks.find(c=>c.validation.status==='FAIL');const [choice,setChoice]=useState<'first'|'last'>('first');if(!failed)return null;const last=checks.at(-1)!;const selected=choice==='first'?failed:last;const local=Object.entries(failed.validation.per_task_results??{}).filter(([id,cs])=>run.task_assessment.some(a=>a.task_id===id&&a.decision!=='KEEP')&&cs.every(c=>c.passed)).map(([id])=>id);const regressions=[...new Set(failed.validation.hard_failures.filter(f=>f.code==='UNRELATED_TASK_REGRESSION').map(f=>f.subject))];const expansions=[...new Set(steps.flatMap(s=>s.action?.scope_expansions?.map(e=>e.entity)??[]))];const alternative=steps.find(s=>s.step>failed.step&&s.option);return <section className="panel feedback-story" data-testid="feedback-story"><span className="eyebrow">AGENT POLICY · CONSTRAINT FEEDBACK</span><h2>全局反馈闭环</h2>{run.seed_origin&&<p className="muted">首份诊断方案来自已有局部修复工具，模型负责送检并依据反馈继续决策。</p>}<div className="feedback-flow"><div><b>① 初始局部方案</b><p>{local.length?`${local.map(entity).join('、')}的已检查约束满足`:'局部方案提交检查'}</p></div><div className="rejected"><b>② 全局校核拒绝</b><p>{regressions.length?`${regressions.map(entity).join('、')}被连带破坏`:'发现全局约束不满足'}</p>{failed.validation.hard_failures.filter(f=>f.code!=='UNRELATED_TASK_REGRESSION').map((f,i)=><p key={i}>{entity(f.subject)}：{reasons[f.code]??'约束不满足'}</p>)}</div><div><b>③ 接收反馈，调整策略</b><p>{expansions.length?`扩大重构范围：加入${expansions.map(entity).join('、')}`:'等待实际范围调整记录'}</p>{alternative&&<p>选择替代方案：{entity(alternative.option!.task)}，加入{alternative.option!.add.map(entity).join('、')||'无新增成员'}。</p>}</div><div className={last.validation.status==='FAIL'?'rejected':'success'}><b>④ 再次全局校核</b><p>{last===failed?'尚未出现第二次校核':validationLabel(last.validation.status)}</p></div></div><div className="segmented"><button className={choice==='first'?'active':''} onClick={()=>setChoice('first')}>首次校核</button><button disabled={last===failed} className={choice==='last'?'active':''} onClick={()=>setChoice('last')}>后续校核</button></div><div className="feedback-inspection" data-testid="feedback-inspection"><b>历史决策 {selected.step} · {validationLabel(selected.validation.status)}</b><p>本次执行的校核记录。</p>{selected.validation.hard_failures.map((f,i)=><p key={i}>{entity(f.subject)}：{reasons[f.code]??'约束未满足'}</p>)}{selected.validation.status!=='FAIL'&&<p>已检查任务 {selected.validation.metrics.validated_tasks} 项，失败 {selected.validation.metrics.failed_constraint_count} 项。</p>}<Technical title="该次校核技术详情" value={selected.validation}/></div></section>}
export function Changes({run}:{run:Run}){const proposal=run.reconstruction_proposal;if(!proposal)return null;const keep=preservation(run);const cost=proposal.cost_breakdown;const committed=Boolean(run.commit);return <section className="panel changes" data-testid="changes"><span className="eyebrow">INCREMENTAL RECONSTRUCTION</span><h2>{committed?'重构方案变更':'待提交方案变更'}</h2><div className="change-grid">{proposal.formation_changes.map(f=><article key={f.formation_id}><h3>{entity(f.formation_id)}</h3>{f.removed_nodes.length>0&&<p className="red-text">退出：{f.removed_nodes.map(entity).join('、')}</p>}{f.added_nodes.length>0&&<p className="green-text">补充进入：{f.added_nodes.map(entity).join('、')}</p>}</article>)}{proposal.task_changes.map(t=><article key={t.task_id}><h3>{entity(t.task_id)}改派</h3><p>{entity(t.before_formation)} → {entity(t.after_formation)}</p></article>)}{proposal.route_changes.map(r=><article key={r.route_id}><h3>{entity(r.task_id)}</h3><p className="green-text">重新规划{entity(r.route_id)}</p><p>{r.reason_codes?.some(c=>c.includes('RESTRICTED'))?'处理限制区域冲突':'根据当前航迹问题调整路径'} · 路径长度 {r.path_length.toFixed(1)} 米</p></article>)}</div><div className="count-strip">{[['任务改派',cost.task_reassignment_count],['新建编队',cost.new_formations],['变化编队',cost.formations_changed],['成员增删',cost.formation_membership_changes],['航迹变化',cost.route_change_count]].map(([label,value])=><Stat key={label} label={String(label)} value={value}/>)}</div>{keep&&<div className="preservation" data-testid="preservation"><h3>方案保持度</h3><div className="keep-facts"><b>{cost.task_reassignment_count===0?'未发生任务改派':`${keep.assignments} 项任务归属保持`}</b><b>{cost.new_formations===0?'未新建编队':`新建 ${cost.new_formations} 个编队`}</b><b>{keep.unaffected.length} 项未受影响任务保持原方案</b><b>{keep.routes.length} 条航迹保持不变</b></div><details className="secondary inset"><summary>受影响任务差异</summary><table><thead><tr><th>任务</th><th>任务归属</th><th>原航迹</th></tr></thead><tbody>{keep.taskRows.map(t=><tr key={t.task}><td>{taskName(t.task,run.before_state)}</td><td>{entity(t.beforeFormation)} → {entity(t.afterFormation)}<br/>{t.assignmentKept?'保持不变':'发生改派'}</td><td>{entity(t.route)} · {t.routeKept?'保持不变':'发生调整'}</td></tr>)}</tbody></table><p>保留的未受影响任务：{keep.unaffected.map(entity).join('、')||'无'}。</p></details><p className="muted">保持度同时比较任务、执行编队与航迹；八维代价按既定优先级比较。</p></div>}<Technical title="扰动向量与原始方案技术详情" value={proposal}/></section>}
export function Outcome({run}:{run:Run}){const m=run.before_after_metrics;return <section className="panel outcome" data-testid="outcome"><span className="kicker">恢复效果</span><h2>{run.commit?'任务恢复结果':'现场状态对比（候选尚未生效）'}</h2><div className="outcome-layout"><table><thead><tr><th>指标</th><th>态势变化后</th><th>{run.commit?'重构完成后':'当前现场'}</th></tr></thead><tbody><tr><td>可行任务</td><td>{m.before.feasible_tasks}/{m.before.task_count}</td><td data-testid="feasible-after">{m.after.feasible_tasks}/{m.after.task_count}</td></tr><tr><td>能力缺口</td><td>{m.before.capability_gap}</td><td>{m.after.capability_gap}</td></tr><tr><td>无效航迹</td><td>{m.before.invalid_routes.length}</td><td>{m.after.invalid_routes.length}</td></tr><tr><td>失效节点</td><td>{m.before.nodes.FAILED??0}</td><td>{m.after.nodes.FAILED??0}</td></tr></tbody></table><div className="scope-stat"><span>实际重构范围</span><strong>{(m.scope_ratio*100).toFixed(2)}%</strong><p>{m.scope_numerator} / {m.scope_denominator} 个实体发生变化</p><small>任务、编队、节点归属/角色、航迹</small></div></div><p className="fact-note">设备故障事实没有被修改，系统通过任务、编队与航迹方案重构恢复任务可执行性。</p><div className="policy-outcome"><span>智能体自主完成：{run.policy_metrics.pure_agent_success?'是':'否'}</span><span>确定性后备介入：{run.policy_metrics.fallback_used?'是':'否'}</span><span>整体完成：{run.policy_metrics.overall_success?'是':'否'}</span></div></section>}
export function ValidationPanel({validation,committed}:{validation:Validation;committed:boolean}){return <section className="panel validation-panel"><span className="eyebrow">GLOBAL CONSTRAINT VALIDATOR</span><h2>全局约束校核</h2><div className={'validation-badge '+(validation.status==='FAIL'?'fail':'pass')} data-testid="validation-status">{validationLabel(validation.status)}</div><div className="count-strip small"><Stat label="检查任务" value={validation.metrics.validated_tasks}/><Stat label="检查编队" value={validation.metrics.validated_formations}/><Stat label="检查航迹" value={validation.metrics.validated_routes}/></div><p><b>{validation.metrics.hard_constraint_count}</b> 项硬约束检查 · 失败 <b>{validation.metrics.failed_constraint_count}</b> · 警告 <b>{validation.metrics.warning_count}</b></p><div className="constraint-categories">{[...new Set(validation.validated_constraints.map(c=>c.category))].map(c=><div className="status-line" key={c}><span>{categories[c]??'其他校核类别'}</span><b className={validation.validated_constraints.some(v=>v.category===c&&!v.passed)?'red-text':'green-text'}>{validation.validated_constraints.some(v=>v.category===c&&!v.passed)?'未通过':'通过'}</b></div>)}</div>{validation.hard_failures.map((f,i)=><p className="red-text" key={i}>{entity(f.subject)}：{reasons[f.code]??'约束未满足'}</p>)}<h3>未建模约束</h3><div className="limitation-list">{validation.not_evaluated.map(v=><span key={v}>{limitations[v]??'其他未建模约束（见详情）'}</span>)}</div><p className="muted">{committed?'已使用原事务机制再次校核并提交。':'当前仅完成候选方案校核。'}失败方案不允许发布；版本过期需重新生成方案。</p><Technical title="全局校核技术详情（含原始状态码）" value={validation}/></section>}
export function Timing({run}:{run:Run}){const t=run.timing;return <section className="panel timing-panel"><h2>执行耗时</h2><div className="timing-row"><span>状态分析</span><b>{time((t.impact_analysis_ms??0)+(t.assessment_ms??0))}</b></div><div className="timing-row"><span>重构算法（候选 / 提案）</span><b>{time(t.option_generation_ms)}</b></div><div className="timing-row"><span>模型策略</span><b>{run.execution_mode==='deterministic_realtime'?'不使用':time(t.model_ms)}</b></div><div className="timing-row"><span>全局校核</span><b>{time(t.validation_ms)}</b></div><div className="timing-row"><span>方案提交（含再次校核）</span><b>{time(t.commit_ms)}</b></div><div className="timing-row total"><span>总耗时</span><b>{time(t.total_ms)}</b></div><p className="muted">模型时间含网络与推理；总耗时不含人工停顿和展示动画。各子阶段可能重叠，不直接相加；候选/提案时间不等于所有确定性计算时间。云模型不承诺低于 5 秒。</p><Technical title="计时、模型用量与求解统计" value={{timing:t,policy:run.policy_metrics}}/></section>}
