import type {Assessment, DemoEvent, Impact, Json, Mode, Run, State, TraceStep, Validation} from './types'

export const modes:Record<Mode,{name:string;note:string}>={
  adaptive_agent:{name:'智能体自适应模式',note:'模型根据任务状态选择重构技能，并根据全局校核反馈调整策略。'},
  bounded_agent:{name:'有界智能体模式',note:'在有限模型预算内决策，未完成时显式切换确定性后备。'},
  deterministic_realtime:{name:'实时确定性模式',note:'使用固定确定性策略恢复方案，0 次模型调用；用于低时延演示与后备。'},
}
export const titles:Record<string,string>={SC01:'关键节点失效',SC02:'冗余能力诊断',SC03:'双节点失效与共享资源竞争',SC04:'环境限制变化与局部航迹重规划',SC05:'任务目标变化',SC06:'节点故障与环境变化混合场景',SC07:'全局冲突反馈与智能重规划',SC08:'综合态势突变'}
export const decisions:Record<string,string>={KEEP:'当前方案仍有效',ADJUST:'需要局部调整',RECONSTRUCT:'需要重构'}
export const strategies:Record<string,string>={IN_PLACE_REPAIR:'原编队局部修复',TASK_REASSIGNMENT:'任务改派',FORMATION_RECONSTRUCTION:'编队重组'}
export const categories:Record<string,string>={preconditions:'提交前提与版本',structure:'结构完整性',membership:'节点归属与可用性',observed_facts:'故障事实保持',metadata:'方案描述一致性',scope:'重构范围一致性',regression:'无关任务回归',formation:'编队约束',time_window:'时间窗口',priority_timing:'优先级与时间约束',capability:'任务能力',resource:'资源约束',route:'航迹有效性'}
export const limitations:Record<string,string>={travel_time:'真实飞行时间',transfer_time:'节点转场时间',dynamic_energy:'动态能耗',formation_geometry:'编队几何',dynamic_scheduling:'动态任务调度'}
export const capability:Record<string,string>={relay:'中继能力',sensor:'传感能力',navigation:'导航能力'}
export const reasons:Record<string,string>={FAILED_NODE_ASSIGNED:'执行编队仍包含失效节点',MEMBER_UNAVAILABLE:'成员不满足任务可用时间窗口',CAPABILITY_SHORTAGE:'任务所需能力不足',UNRELATED_TASK_REGRESSION:'其他任务被方案连带破坏',ROUTE_RESTRICTED_AREA_COLLISION:'航迹与限制区域冲突',ROUTE_RESTRICTED_AREA_CONFLICT:'航迹与限制区域冲突',ROUTE_ENDPOINT_MISMATCH:'航迹终点与任务目标不一致',RESOURCE_SHORTAGE:'任务可用资源不足',SHARED_RESOURCE_OVERCOMMITTED:'共享资源被超额占用',FORMATION_MISSING:'任务缺少执行编队',MINIMUM_NODE_COUNT:'可用成员数量不足',TASK_TIME_CONFLICT:'任务执行时间冲突',TASK_DEADLINE_EXPIRED:'任务时间窗口已经结束',FORMATION_CAPABILITY_SHORTAGE:'编队最低能力不满足'}
export const tools:Record<string,string>={'Scope':'确定局部重构范围','Candidate filtering':'候选资源筛选','Strategy / Solver':'分层策略与算法求解','Reservations':'预留候选资源','Route decisions':'航迹影响检测','Validation':'全局约束校核','Validate / Commit':'校核并提交现场方案',FINALIZE_PROPOSAL:'提交方案接受全局校核',get_reconstruction_options:'获取可行重构选项',apply_reconstruction_option:'应用所选重构方案',try_in_place_repair:'原编队局部修复',find_task_reassignment_options:'查找任务改派选项',try_formation_reconstruction:'编队重组',generate_candidates:'候选资源筛选',replan_route:'航迹重新规划',detect_route_impacts:'航迹影响检测',validate_proposal:'全局约束校核',commit_validated_proposal:'提交已校核方案',inspect_current_state:'检查当前状态',get_outstanding_violations:'获取未解决约束',Inspect:'检查当前状态'}
export const stages:Record<string,string>={total:'全部节点',status:'状态可用',capability_relevance:'能力相关',window:'可用时间窗口',time_conflict:'无任务时间冲突',resource:'资源满足',critical_assignment:'不占用关键任务资源',scope_and_ownership:'范围与归属允许'}
export const time=(ms:number|undefined)=>ms===undefined?'未单列':ms>=1000?`${(ms/1000).toFixed(2)} 秒`:`${ms.toFixed(1)} 毫秒`
export const object=(v:Json|undefined|null):Record<string,Json>=>v&&typeof v==='object'&&!Array.isArray(v)?v:{}
export const list=(v:Json|undefined):Json[]=>Array.isArray(v)?v:[]
export function entity(id:string|null|undefined){if(!id)return '未分配';const prefix=id.split(':')[0];const value=id.includes(':')?id.split(':').at(-1)!:id;const kind=({task:'任务',formation:'编队',node:'节点',route:'航迹',environment:'限制区域'} as Record<string,string>)[prefix]??(/^T\d/.test(id)?'任务':/^F\d/.test(id)?'编队':/^U\d/.test(id)?'节点':/^R\d/.test(id)?'航迹':'对象');return `${kind} ${value}`}
export function taskName(id:string,state?:State){const task=state?.tasks.find(t=>t.id===id);return `任务 ${id}${task?.name?'｜'+(({repair:'修复'} as Record<string,string>)[task.name]??task.name):''}`}
export const validationLabel=(status:string)=>status==='FAIL'?'全局校核未通过':status==='PASS_WITH_LIMITATIONS'?'已通过当前已建模约束校核':status==='PASS'?'全局校核通过':'尚未获得校核结论'
export const runLabel=(status:string)=>({RUNNING:'正在重构',READY:'方案待提交',COMMITTED:'已提交',FAILED:'未完成',NO_RECONSTRUCTION_REQUIRED:'无需重构'} as Record<string,string>)[status]??'状态待确认'
export function eventText(e:DemoEvent){switch(e.type){case 'NodeFailure':return `${entity(e.node_id)}发生失效`;case 'NodeDegradation':return `${entity(e.node_id)}能力降级`;case 'RestrictedAreaAdd':return `新增限制区域 ${e.region?.id??''}`;case 'RestrictedAreaRemove':return `移除限制区域 ${e.region_id??''}`;case 'TaskPriorityChange':return `${entity(e.task_id)}优先级调整为 ${e.priority}`;case 'TargetMove':return `${entity(e.task_id)}目标位置变化`;case 'TaskAdd':return `新增${entity(e.task?.id)}`;case 'TaskCancel':return `取消${entity(e.task_id)}`;default:return '态势事件变化（查看技术详情）'}}
export function eventCounts(events:DemoEvent[]){const count=(type:string)=>events.filter(e=>e.type===type).length;return [count('NodeFailure')&&`${count('NodeFailure')} 个节点失效`,count('RestrictedAreaAdd')&&`新增 ${count('RestrictedAreaAdd')} 个限制区域`,count('TaskPriorityChange')&&`${count('TaskPriorityChange')} 项任务优先级变化`,count('TaskAdd')&&`新增 ${count('TaskAdd')} 项任务`,count('TaskCancel')&&`取消 ${count('TaskCancel')} 项任务`,count('TargetMove')&&`${count('TargetMove')} 项任务目标变化`,count('NodeDegradation')&&`${count('NodeDegradation')} 个节点降级`,count('RestrictedAreaRemove')&&`移除 ${count('RestrictedAreaRemove')} 个限制区域`].filter(Boolean).join('；')}
export const affectedTasks=(impacts:Impact[])=>[...new Set(impacts.flatMap(i=>i.affected_tasks))]
export function capabilityRows(a:Assessment){return Object.entries(object(object(a.constraints.find(c=>c.type==='capability')?.details).capabilities)).map(([key,value])=>({key,required:object(value).required,available:object(value).available,gap:object(value).gap}))}
export function issueText(a:Assessment){const gaps=capabilityRows(a).filter(c=>Number(c.gap)>0);if(gaps.length)return gaps.map(g=>`${capability[g.key]??'能力 '+g.key}不足：需求 ${g.required} / 当前可用 ${g.available} / 缺口 ${g.gap}`).join('；');const fail=a.constraints.filter(c=>c.status==='FAIL');return fail.length?(a.reason_codes.map(c=>reasons[c]).filter(Boolean).join('；')||fail.map(c=>`${categories[c.type]??'约束'}不满足`).join('；')):decisions[a.decision]??'评估结果见详情'}
export function readablePath(path:string[],events:DemoEvent[]){return path.map((p,index)=>{if(index===0){const e=events.find(e=>e.node_id&&p===`node:${e.node_id}`||e.region?.id&&p===`environment:${e.region.id}`);if(e)return eventText(e)}if(p.startsWith('capability:'))return capability[p.split(':').at(-1)!]??'关联能力';return entity(p)})}
// Select an existing P2 path per affected task; never infer new dependency edges.
export function impactChains(impacts:Impact[]){const result:{task:string;path:string[];eventIds:string[]}[]=[];for(const task of affectedTasks(impacts)){const related=impacts.filter(i=>i.affected_tasks.includes(task));const paths=related.flatMap(i=>i.propagation_paths).filter(p=>p.at(-1)===`task:${task}`);paths.sort((a,b)=>b.length-a.length);if(paths[0])result.push({task,path:paths[0],eventIds:related.map(i=>i.event_id)})}return result}
export type DependencyGraphNode={id:string;label:string;kind:'source'|'dependency'|'constraint'|'task';column:number}
export type DependencyGraphEdge={from:string;to:string}
export function dependencyGraph(impacts:Impact[],events:DemoEvent[]){
 const paths=impacts.flatMap(i=>i.propagation_paths)
 const nodeMap=new Map<string,DependencyGraphNode>(),edgeMap=new Map<string,DependencyGraphEdge>()
 const kind=(id:string):DependencyGraphNode['kind']=>id.startsWith('task:')?'task':id.startsWith('capability:')?'constraint':id.startsWith('formation:')||id.startsWith('route:')?'dependency':'source'
 const column=(value:DependencyGraphNode['kind'])=>({source:0,dependency:1,constraint:2,task:3})[value]
 for(const path of paths){
  path.forEach(id=>{if(!nodeMap.has(id)){const nodeKind=kind(id);nodeMap.set(id,{id,label:readablePath([id],events)[0],kind:nodeKind,column:column(nodeKind)})}})
  for(let i=0;i<path.length-1;i++){const edge={from:path[i],to:path[i+1]};edgeMap.set(`${edge.from}>${edge.to}`,edge)}
 }
 return {nodes:[...nodeMap.values()],edges:[...edgeMap.values()]}
}
export function changedRoutes(before:State,after:State){return new Set(after.routes.filter(r=>JSON.stringify(before.routes.find(b=>b.id===r.id))!==JSON.stringify(r)).map(r=>r.id))}
export function switchedNodes(before:State,after:State){const map=(s:State)=>new Map(s.formations.flatMap(f=>f.node_ids.map(n=>[n,f.id] as const)));const a=map(before),b=map(after);return new Set([...new Set([...a.keys(),...b.keys()])].filter(n=>a.get(n)!==b.get(n)))}
export function preservation(run:Run){const before=run.before_state,after=run.status==='READY'?run.candidate_state:run.after_state;if(!after)return null;const impacted=new Set(affectedTasks(run.impact_analysis));const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);const unaffected=before.tasks.filter(t=>!impacted.has(t.id)).filter(t=>{const next=after.tasks.find(n=>n.id===t.id);return same(t,next)&&same(before.formations.find(f=>f.id===t.formation_id),after.formations.find(f=>f.id===next?.formation_id))&&same(before.routes.find(r=>r.id===t.route_id),after.routes.find(r=>r.id===next?.route_id))});return {unaffected:unaffected.map(t=>t.id),routes:before.routes.filter(r=>same(r,after.routes.find(n=>n.id===r.id))).map(r=>r.id),assignments:before.tasks.filter(t=>t.formation_id===after.tasks.find(n=>n.id===t.id)?.formation_id).length,taskRows:before.tasks.filter(t=>impacted.has(t.id)).map(t=>{const next=after.tasks.find(n=>n.id===t.id);return {task:t.id,beforeFormation:t.formation_id,afterFormation:next?.formation_id,route:t.route_id,routeKept:same(before.routes.find(r=>r.id===t.route_id),after.routes.find(r=>r.id===next?.route_id)),assignmentKept:t.formation_id===next?.formation_id}})}}
export function feedbackChecks(steps:TraceStep[]){return steps.flatMap(s=>s.feedback?[{step:s.step,validation:s.feedback as unknown as Validation}]:[])}
export function decisionSummary(s:TraceStep){if(s.kind==='LIVE_TRANSACTION')return '全局再次校核后，将方案发布到现场态势。';if(s.feedback&&object(s.feedback).status==='FAIL')return '当前方案未通过全局校核，需根据结构化反馈继续修正。';if(s.option)return `从算法提供的选项中选择“${strategies[s.option.strategy]??'重构方案'}”，用于${entity(s.option.task)}。`;const expansions=s.action?.scope_expansions??[];if(expansions.length)return `根据校核反馈扩大检查范围：${[...new Set(expansions.map(e=>entity(e.entity)))].join('、')}。`;if(s.tool==='replan_route')return '调用航迹规划算法，计算任务可用的替代航迹。';if(s.tool==='FINALIZE_PROPOSAL')return '将当前方案交由独立全局校核器检查。';return `执行${tools[s.tool]??'重构工具'}，结果来自实际运行记录。`}
